name: skill_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5
  provider: ^6.0.2
  badges: ^3.0.2
  uuid: ^3.0.6
  webview_flutter: ^4.0.2
  firebase_messaging: ^14.2.1
  flutter_svg: ^1.1.0
  intl: ^0.18.0
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^4.0.1
  flip_card: ^0.7.0
  marquee: ^2.2.3
  animated_text_kit: ^4.2.2
  http: ^0.13.4
  flutter_radar_chart: ^0.2.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
